name: Package and Release VS Code Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.3.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm install
        working-directory: vscode-extension

      - name: Run tests (with xvfb)
        run: xvfb-run -a npm test
        working-directory: vscode-extension

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package
        working-directory: fhir-mapbuilder-validation

      - name: Ensure target directory exists in extension
        run: mkdir -p vscode-extension/target

      - name: Move JAR to VS Code extension
        run: mv fhir-mapbuilder-validation/target/fhir-mapbuilder-validation.jar vscode-extension/target

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package --baseContentUrl https://github.com/aphp/fhir-mapbuilder.git
        working-directory: vscode-extension

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: vscode-extension/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
